In [1]:
import numpy as np

In [2]:
# how to make array in python
x = np.array([[3,4,5],1])

C:\Users\ddugky\AppData\Local\Temp/ipykernel_2052/2472735255.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x = np.array([[3,4,5],1])


In [3]:
x

array([list([3, 4, 5]), 1], dtype=object)

In [4]:
type(x)

numpy.ndarray

In [5]:
x.shape

(2,)

In [6]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
s = np.array([8,7,5])
s

array([8, 7, 5])

In [9]:
s[1]

7

In [10]:
s[0:3]

array([8, 7, 5])

In [11]:
s[1]=0

In [12]:
s

array([8, 0, 5])

In [13]:
s[3]=2

IndexError: index 3 is out of bounds for axis 0 with size 3

In [14]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
a[0][0]

1

In [16]:
a[0][0]=10

In [17]:
a

array([[10,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [18]:
x = np.array([1,23,3])

In [19]:
x

array([ 1, 23,  3])

In [20]:
x.shape

(3,)

In [21]:
x.size

3

In [22]:
x.ndim

1

In [23]:
a = np.array([[8,9,0],[7,6,5],[1,2,3]])

In [24]:
a

array([[8, 9, 0],
       [7, 6, 5],
       [1, 2, 3]])

In [25]:
a.ndim

2

In [26]:
a.shape

(3, 3)

In [27]:
a.size

9

In [28]:
a

array([[8, 9, 0],
       [7, 6, 5],
       [1, 2, 3]])

In [29]:
a.sum(axis=0)

array([16, 17,  8])

In [30]:
a.sum(axis=1)

array([17, 18,  6])

In [31]:
#array with the help of some methods & attributes
#zeros
# ones
#arange

s = np.array([0,0,0])

In [32]:
s

array([0, 0, 0])

In [38]:
#zeroes
x = np.zeros(200)

In [39]:
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
x = np.zeros((3,5))

In [50]:
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [62]:
x=np.ones((10,3,5))

In [63]:
x

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [85]:
# WAP and make an array of 3 by 7 of both zero and one.
# 0,1 
#arange
a = np.arange(30,70,12)

In [86]:
a

array([30, 42, 54, 66])

In [ ]:
np.arange()