In [2]:
# Searching
# sorting
# arg
import numpy as np
arr = np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
arr.ndim

1

In [5]:
arr = np.array([[1,2,3,4]])

In [6]:
arr

array([[1, 2, 3, 4]])

In [7]:
arr.ndim

2

In [11]:
arr = np.array([[1,2,3,4],[2,3,4]])

C:\Users\ddugky\AppData\Local\Temp/ipykernel_4632/2578901277.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[1,2,3,4],[2,3,4]])


In [12]:
arr

array([list([1, 2, 3, 4]), list([2, 3, 4])], dtype=object)

In [13]:
arr.ndim

1

In [47]:
arr = np.array([4])

In [48]:
arr

array([4])

In [49]:
arr.ndim

1

In [50]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [51]:
arr


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [52]:
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [55]:
arr.sum(axis=1)

array([[12, 15, 18]])

In [61]:
arr.sum(axis=0)

array([12, 15, 18])

In [57]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [58]:
arr.sum(axis=0)

array([12, 15, 18])

In [59]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [62]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])


In [63]:
arr.sum(axis=1)

array([[12, 15, 18]])

In [64]:
arr.sum(axis=2)

array([[ 6, 15, 24]])

In [65]:
x = [23,34]+[45,6]

In [66]:
x

[23, 34, 45, 6]

In [67]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[3,4,5]])

In [71]:
a+b
a-b
a*b
a/b

array([[-6, -6, -6],
       [ 1,  1,  1]])

In [74]:
#how to transpose a matrix
a

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [86]:
#searching
a = np.array([1000,999,80,89,90,78,99,100])
arr = np.where(a%2!=0)

In [87]:
arr

(array([1, 3, 6], dtype=int64),)

In [88]:
a

array([1000,  999,   80,   89,   90,   78,   99,  100])

In [89]:
a.sort()

In [90]:
a

array([  78,   80,   89,   90,   99,  100,  999, 1000])

In [91]:
arr

(array([1, 3, 6], dtype=int64),)

In [102]:
arr = np.array([[100,100,300],[400,600,600],[700,800,800]])

In [103]:
arr

array([[100, 100, 300],
       [400, 600, 600],
       [700, 800, 800]])

In [104]:
arr.min()

100

In [105]:
arr.max()

800

In [106]:
arr

array([[100, 100, 300],
       [400, 600, 600],
       [700, 800, 800]])

In [107]:
#index
arr.argmax()

7

In [108]:
arr.argmin()

0

In [109]:
# arr.argsort()
arr

array([[100, 100, 300],
       [400, 600, 600],
       [700, 800, 800]])

In [110]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [122]:
arr = np.array([[100,800,300],[900,600,700],[700,800,800]])

In [123]:
arr

array([[100, 800, 300],
       [900, 600, 700],
       [700, 800, 800]])

In [124]:
arr.argmax()

3

In [125]:
arr.argmin()

0

In [126]:
arr.argsort()

array([[0, 2, 1],
       [1, 2, 0],
       [0, 1, 2]], dtype=int64)